Edotm fork/optimize1
wiremod/wire-extras pull request #101
Opened 2021-04-11 11:45 UTC by EdoTM

2021-04-11 22:12 UTC, TomyLobo commented
Well anyone can replace one function call with another, so just to be sure you understand what you're doing, describe what `SetNetworkedBeamString` is.

2021-04-11 22:59 UTC, thegrb93 commented
SetNetworkedBeamString are just wire's implementation of SetNWString that was removed a long time ago.

2021-04-11 22:59 UTC, EdoTM commented
Networked Beams were an attempt to optimize the data flow between server and client when treating large data (there's also a description [**here**](https://github.com/wiremod/wire/blob/e0224feb491621efe7c5d41849328df601a1a6cc/lua/wire/beam_netvars.lua), a more-than-10-years-old file) but they eventually got removed (along with the NW Beam library) by AbigailBuccaneer in 2015.
Some wire extras items (such as doors and door controllers) still use these, and they do generate errors when you try to use them (actually, in some cases you **can't** use them due to these errors). 

A fix would be changing `SetNetworkedBeamString` to `SetNWString`, as it has already been done in #74. I personally tried doors and door controllers, and with this fix they work smoothly without a single error.

2021-04-11 23:00 UTC, thegrb93 commented
I'll have time to review tomorrow.

2021-04-12 00:08 UTC, TomyLobo commented
@thegrb93 You do realize that you giving any kind of hint on what beams are kinda defeats the point of that test :)
@EdoTM passed with flying colors, though :)

2021-04-12 00:10 UTC, thegrb93 commented
Oh, thought you were asking rather than testing

2021-04-12 08:34 UTC, EdoTM commented
I'm now removing unused `net.Write*`/`Read*`, and I noticed that in `wire_modular_panel.lua` there's a strange behavior in usermessages and servermessages. On [line 325](https://github.com/wiremod/wire-extras/blob/653a1f5830071ce1f88cae57a211aa8948c50db9/lua/weapons/gmod_tool/stools/wire_modular_panel.lua#L325) of the file that is currently on the repository, a ***user***message named `smsgModularPanel` is initialized (the name is the same of the servermessage defined on [line 204](https://github.com/wiremod/wire-extras/blob/653a1f5830071ce1f88cae57a211aa8948c50db9/lua/weapons/gmod_tool/stools/wire_modular_panel.lua#L204). They are correlated, but I don't know if the fact of them having an identical name is actually intentional), but there's no `usermessage.Hook("smsgModularPanel", ...)` or `umsgModularPanel` in any file. 
Am I missing something?

2021-04-13 03:11 UTC, thegrb93 requested changes

2021-04-13 03:12 UTC, thegrb93 commented
Looks like a 1 to 1 conversion and looks fine. If you wouldn't mind just cleaning up the unneeded comments and revert the GetConVar change, it will be perfect.

2021-04-13 08:07 UTC, EdoTM commented on lua/entities/base_wdr_entity/init.lua
> +			local dist = self:GetPos():Distance(v:GetPos()) / GetConVar("sv_wdrk_scale"):GetInt()
Done!

2021-04-13 08:08 UTC, EdoTM commented on lua/entities/gmod_wire_adv_hudindicator/cl_init.lua
> +//local hudy = 0
I was leaving them to highlight what I was changing, I now removed them

2021-04-13 08:10 UTC, EdoTM commented
Removed unnecessary comments and reverted `GetConVar(...):GetInt()` with `GetConVarNumber(...)`

2021-04-13 19:55 UTC, thegrb93 commented
Thanks. Looks good

2021-04-13 19:55 UTC, merged